server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
  port: 8888

spring:
  application:
    name: cms-admin
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    property-naming-strategy: SNAKE_CASE
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  redis:
    timeout: 60000ms

otel:
  traces:
    exporter: none
  metrics:
    exporter: none
  logs:
    exporter: none

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/x_admin?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root@admin
  redis:
    host: 127.0.0.1
    password: redis
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/x_admin?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root@admin
  redis:
    host: 127.0.0.1
    password: redis
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/x_admin?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root@admin
  redis:
    host: 127.0.0.1
    password: redis
